"""first

Revision ID: ecdc4a6c0e10
Revises: 
Create Date: 2024-03-27 20:28:03.525708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecdc4a6c0e10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('stars', sa.Integer(), server_default='0', nullable=False),
    sa.Column('position_cur', sa.Integer(), server_default='0', nullable=False),
    sa.Column('position_prev', sa.Integer(), server_default='0', nullable=False),
    sa.Column('watchers', sa.Integer(), server_default='0', nullable=False),
    sa.Column('forks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('open_issues', sa.Integer(), server_default='0', nullable=False),
    sa.Column('language', sa.String(), server_default='english', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo')
    )
    op.create_table('commits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commits')
    op.drop_table('repos')
    # ### end Alembic commands ###
